build-job:
  stage: build
  script:
    - echo "building..."

breaking-changes-job:
  stage: check for API Breaking Changes
  image: 'tufin/oasdiff:main'
  script:
    - oasdiff breaking specs/base specs/revision
